-- errormsg.lua
ErrorCode = {}

ErrorCode.ACCOUNT_REPEAT = 1
ErrorCode.DBSERVICE_ERROR = 99
ErrorCode.NO_ACCOUNT = 101
ErrorCode.PASSWORD_ERROR = 102
ErrorCode.HAS_ONLINE = 103
ErrorCode.NO_USER_ID = 105
ErrorCode.NOT_ONLINE = 106

ErrorCode.ROOM_NOT_FOUND = 201
ErrorCode.ROOM_FULL = 202

ErrorCode.GOLD_NOT_ENOUGH = 301
ErrorCode.BANKER_NO_BET = 401
ErrorCode.NOT_BANKER = 402
ErrorCode.NOT_IN_QUEUE = 403
ErrorCode.UR_BANKER = 404
ErrorCode.HAS_IN_QUEUE = 405
ErrorCode.TUIBING_ROOMCLOSE = 406

-- mahjong
ErrorCode.MAHJONG_ROOM_FULL = 501
ErrorCode.MAHJONG_PLAYER_NOT_FOUND = 502
ErrorCode.MAHJONG_MJ_NOT_FOUND = 503
ErrorCode.MAHJONG_ERROR_COMMAND = 504

-- GM
ErrorCode.PERMISSION_DENIED = 901
ErrorCode.LOGTYPE_ERROR = 902